import { defineType, defineField } from "sanity";

export const product = defineType({
  name: "product",
  title: "Ürün",
  type: "document",
  groups: [
    { name: "content", title: "İçerik" },
    { name: "media", title: "Görseller" },
    { name: "details", title: "Detaylar" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Ürün Adı",
      type: "string",
      group: "content",
      validation: (r) => r.required().min(3).max(120),
    }),
    defineField({
      name: "slug",
      title: "URL Slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
      validation: (r) => r.required(),
    }),
    defineField({
      name: "brand",
      title: "Marka",
      type: "reference",
      to: [{ type: "brand" }],
      group: "details",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "category",
      title: "Kategori",
      type: "reference",
      to: [{ type: "category" }],
      group: "details",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "oemNumbers",
      title: "OEM Parça Numaraları",
      type: "array",
      group: "details",
      of: [{ type: "string" }],
      description: "VAG orijinal parça kodları (ör: 5G0 698 151 A)",
    }),
    defineField({
      name: "price",
      title: "Fiyat (TL)",
      type: "number",
      group: "details",
      description: "Opsiyonel — boş bırakılırsa WhatsApp'tan teklif alınır",
    }),
    defineField({
      name: "shortDescription",
      title: "Kısa Açıklama",
      type: "text",
      rows: 2,
      group: "content",
      validation: (r) => r.max(200),
    }),
    defineField({
      name: "description",
      title: "Detaylı Açıklama",
      type: "array",
      of: [{ type: "block" }],
      group: "content",
    }),
    defineField({
      name: "features",
      title: "Özellikler",
      type: "array",
      of: [{ type: "string" }],
      group: "content",
    }),
    defineField({
      name: "specifications",
      title: "Teknik Özellikler",
      type: "array",
      of: [
        {
          type: "object",
          fields: [
            { name: "key", title: "Özellik", type: "string" },
            { name: "value", title: "Değer", type: "string" },
          ],
          preview: { select: { title: "key", subtitle: "value" } },
        },
      ],
      group: "details",
    }),
    defineField({
      name: "compatibleModels",
      title: "Uyumlu Modeller",
      type: "array",
      of: [{ type: "string" }],
      group: "details",
      description: "VW Golf 7, Audi A3 8V vb.",
    }),
    defineField({
      name: "images",
      title: "Ürün Görselleri",
      type: "array",
      group: "media",
      of: [
        {
          type: "image",
          options: { hotspot: true },
          fields: [
            { name: "alt", title: "Alt Text (SEO)", type: "string" },
          ],
        },
      ],
      validation: (r) => r.min(1),
    }),
    defineField({
      name: "tags",
      title: "Etiketler",
      type: "array",
      of: [{ type: "reference", to: [{ type: "tag" }] }],
      group: "details",
    }),
    defineField({
      name: "isFeatured",
      title: "Öne Çıkan",
      type: "boolean",
      group: "details",
      initialValue: false,
    }),
    defineField({
      name: "metaTitle",
      title: "SEO Title",
      type: "string",
      group: "seo",
      validation: (r) => r.max(60),
    }),
    defineField({
      name: "metaDescription",
      title: "SEO Description",
      type: "text",
      rows: 3,
      group: "seo",
      validation: (r) => r.max(160),
    }),
    defineField({
      name: "publishedAt",
      title: "Yayın Tarihi",
      type: "datetime",
      group: "details",
      initialValue: () => new Date().toISOString(),
    }),
  ],
  preview: {
    select: {
      title: "title",
      subtitle: "brand.name",
      media: "images.0",
    },
  },
  orderings: [
    { title: "Yayın Tarihi (Yeni)", name: "publishedAtDesc", by: [{ field: "publishedAt", direction: "desc" }] },
    { title: "Ürün Adı (A-Z)", name: "titleAsc", by: [{ field: "title", direction: "asc" }] },
  ],
});
